- name: Gather info
  hosts: all
  tasks:
    - debug: msg="Number of CPUs:{{ansible_processor_cores}}"
    - debug: msg="Host name:{{ansible_hostname}}"
    - debug: msg="Host IP:{{ansible_default_ipv4.address}}"
    - debug: msg="Total RAM:{{ansible_memtotal_mb}} mb"
