- hosts: all
  become: true
  become_user: root

  tasks:
   - name: Installation
     roles:
       - java
       - tomcat
       - nginx

   - name: Verification
     roles:
       - nginx_test
       - java_test
       - tomcat_test