---
# tasks file for tomcat
- name: Add group {{tomcat_as_group}}
    group: 
      name: {{tomcat_as_group}}
      state: present

- name: Add user {{tomcat_user}}
    user:
      name: {{tomcat_user}}
      state: present

 - name: Download Tomcat
    get_url:
      url: http://archive.apache.org/dist/tomcat/tomcat-{{tomcat_major_version}}/v{{tomcat_version}}/bin/apache-tomcat-{{tomcat_version}}.tar.gz
      dest: {{tomcat_home}}apache-tomcat-{{tomcat_version}}.tar.gz

- name: Extract Tomcat archive
    unarchive:
      src: {{tomcat_home}}apache-tomcat-{{tomcat_version}}.tar.gz
      dest: {{tomcat_home}}
      remote_src: true

- name: Change directory name
    shell: mv -n {{tomcat_home}}apache-tomcat-{{tomcat_version}} {{tomcat_home}}{{tomcat_version}}/      

- name: Change ownership, group and mode set
    file:
      path: {{tomcat_home}}apache-tomcat-{{tomcat_version}}/
      owner: {{tomcat_user}}
      group: {{tomcat_as_group}}
      recurse: yes
      mode: u=rwx,g=rwx,o=rwx
      state: directory

- name: Create systemd unit file for Tomcat 
    shell: echo -e 
     " [Unit]\n
     Description=Apache Tomcat Web Application Container\n
     [Service]\n
     Type=forking\n
     Environment=JAVA_HOME=/usr/lib/jvm/jre-1.8.0\n
     Environment=CATALINA_PID={{tomcat_home}}{{tomcat_version}}/temp/tomcat.pid
     Environment=CATALINA_HOME={{tomcat_home}}{{tomcat_version}}\n
     Environment=CATALINA_BASE={{tomcat_home}}{{tomcat_version}}\n
     ExecStart={{tomcat_home}}{{tomcat_version}}/bin/startup.sh\n
     ExecStop=/bin/kill -15 $MAINPID\n
     User={{tomcat_user}}\n
     Group={{tomcat_as_group}}\n
     [Install]\n
     WantedBy=multi-user.target"
     >> /etc/systemd/system/tomcat.service

    notify:
      - system daemon-reload



- name: Enable service Tomcat and start it
    service:
      name: tomcat
      enabled: yes
      state: started
      notify: 
        -systemctl restart tomcat

- shell: systemctl status tomcat
  register: result

- debug:
    var: result
      